### ISSUE TITLE
Do reads need to be aligned with "--outSAMattributes NH HI AS nM NM MD jM jI XS" ?

### ISSUE THREAD

**Issue by cmonger** [dieterich-lab/circtools#74]
I have been trying to follow the DCC & FUCHs pipeline but am encountering errors with the FUCH stage. 

I aligned my reads as described in the DCC https://github.com/dieterich-lab/DCC and circtools manual pages: http://docs.circ.tools/en/latest/Detect.html#mapping-against-the-reference-genome

```
Traceback (most recent call last):
  File "/home/craig/.local/bin/FUCHS", line 11, in <module>
    load_entry_point('FUCHS==0.2.0', 'console_scripts', 'FUCHS')()
  File "/home/craig/git/craig/circRNA/pyenv/lib/python2.7/site-packages/FUCHS-0.2.0-py2.7.egg/FUCHS/FUCHS.py", line 231, in main
    se.run()
  File "/home/craig/git/craig/circRNA/pyenv/lib/python2.7/site-packages/FUCHS-0.2.0-py2.7.egg/FUCHS/detect_skipped_exons.py", line 168, in run
    p.map(self.run_parallel, files)
  File "/home/craig/git/craig/circRNA/pyenv/lib/python2.7/site-packages/pathos-0.2.3-py2.7.egg/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/craig/git/craig/circRNA/pyenv/lib/python2.7/site-packages/multiprocess-0.70.7-py2.7-linux-x86_64.egg/multiprocess/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/craig/git/craig/circRNA/pyenv/lib/python2.7/site-packages/multiprocess-0.70.7-py2.7-linux-x86_64.egg/multiprocess/pool.py", line 572, in get
    raise self._value
KeyError: "tag 'jI' not present"
```

The FUCHS manual https://github.com/dieterich-lab/FUCHS has the "--outSAMattributes NH HI AS nM NM MD jM jI XS" flag in its alignment instructions. Does this need to be used during alignment for the circtools pipeline?

**Comment by tjakobi** [comment]
Dear @cmonger,

sorry for the late response, somehow got pushed down in the inbox.

You are right, indeed the script linked in the circtools manual and that I use for routine alignments has the following STAR flag set:

` --outSAMattributes NH   HI   AS   nM   NM   MD   jM   jI   XS`

Link: https://raw.githubusercontent.com/dieterich-lab/bioinfo-scripts/master/slurm_circtools_detect_paired_mapping.sh

I have to add this to the doc pages, this seems to have been lost during writing the documentation.

Cheers,
Tobias
